version: '3'
services:
  restql-api:
    image: b2wdigital/restql-http:latest
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017/restql
    volumes:
      - ./restql.yml:/usr/src/restql-http/restql.yml
    links:
      - mongodb

  restql-manager:
    image: b2wdigital/restql-manager:latest
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017/restql
      - RESTQL_SERVER_URL=http://restql-api:9000
    links:
      - mongodb
      - restql-api

  mongodb:
    image: mongo:latest

  server:
    image: nginx:alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    links:
      - restql-api
      - restql-manager
    ports:
      - 80:80

