version: '3'
services:
  restql-api:
    image: b2wdigital/restql-http:latest
    restart: always
    ports:
      - "9000:9000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/restql
    links:
      - mongodb

  restql-manager:
    image: b2wdigital/restql-manager:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/restql
      - RESTQL_SERVER_URL=http://restql-api:9000
    links:
      - mongodb
      - restql-api

  mongodb:
    image: mongo:latest
